name: Archipelago Log to Discord

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  post-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: cache.json
          key: log-cache

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" 
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py

      - name: Save cache
        uses: actions/cache@v4
        with:
          path: cache.json
          key: log-cache
